### ISSUE TITLE
Dead link to HowToWriteGoodTestCases

### ISSUE THREAD

**Issue by tpatja-broadsoft** [robotframework/robotframework.github.com#15]
https://code.google.com/p/robotframework/wiki/HowToWriteGoodTestCases is no longer available. Is the content available somewhere else on the web?

**Comment by pekkaklarck** [comment]
It seems Google Code has now been closed down and archived. That's not a surprise, they told it will happen in January, an we have moved most of the stuff away from there already.

The problem is that for some reason old Robot Framework pages aren't shown in the archive but instead at https://code.google.com/p/robotframework you get a link pointing to GitHub. This means that this how-to and few other remaining pages that contain valuable information are not accessible. I will contact Google Code archive team and see could this redirection be disabled. A longer team solution is moving the how-to into a new location.

In the meantime we'll remove the broken link and add a link to [Does and Don'ts slides](http://www.slideshare.net/pekkaklarck/robot-framework-dos-and-donts). They were already linked from the how-to and should have been added to robotframework.org already earlier.

**Comment by pekkaklarck** [comment]
I sent an email and asked the redirection to be removed. Hopefully I also get an answer at some point...

I also studied how to get the data from the archive if we get no reply or if the reply is "no". The data [is available via JSON API](https://code.google.com/archive/schema). After a little trial and error I was able to get this particular wiki page content using this URL:
https://storage.googleapis.com/google-code-archive/v2/code.google.com/robotframework/wiki/HowToWriteGoodTestCases.wiki

The wiki has a custom format, but there [is a tool to convert it to Markdown](https://code.google.com/p/support-tools/wiki/WikiToMarkdownTool).

**Comment by tpatja-broadsoft** [comment]
Thank you for looking into this so quickly.

Maybe the Markdown converted doc can be added to git under eg. robotframework/doc/how_to_write_good_test_cases.md and the link made to point to the github blob link for it?

**Comment by pekkaklarck** [comment]
Yeah, need to decided where to put the how-to. We have at least these possibilities:

- `robotframework/doc` like proposed by @tpatja-broadsoft above
- Into a new HowToWriteGoodTestCases repository
- Into a new generic repository for howtos/tutorials like this.
- Into wiki under robotframework repository.
- Somewhere else.

We also have Python tutorial currently under `robotfamework/doc/python`. Should probably have them both in the same location. QuickStartGuide currently available as a separete repo is also somewhat related.

**Comment by pekkaklarck** [comment]
Yay, I got a reply from Google Code! They said that the project was in somewhat weird state and they restored the old pages at http://code.google.com/p/robotframework/. Unfortunately browsers seem to pretty aggressively cache redirects, so if you visited these pages while they redirected to http://code.google.com/arcihive/p/robotframework/ you may still be redirected there. Emptying caches or using a URL with query parameters like http://code.google.com/p/robotframework/a=1 ought to fix the problem. For example, the howto that started this whole discussion can be accessed at https://code.google.com/p/robotframework/wiki/HowToWriteGoodTestCases?a=1

Because the original HowTo link ought to work for users who haven't visited during the last few days, I guess it is OK to leave it at http://robotframework.org too for now. I'll try to get it recreated today (I think I'll create a new repo for it) and then the link can be updated. Dos and Don'ts slides should be added there separately anyway.

**Comment by pekkaklarck** [comment]
I have now recreated this how-to here:
https://github.com/robotframework/HowToWriteGoodTestCases

Typo fixes, comments, etc. are highly appreciated but belong to that project's issue tracker.

@Tattoo, could you update the link to the how-to? Please add a separate link to Dos and Don'ts too.

**Comment by pekkaklarck** [comment]
Thanks @tattoo! Was thinking should how-to be before slides, though? The latter could then have doc like "presentation loosely based on the above how-to".

**Comment by Tattoo** [comment]
I had that order originally, but since the description in Installation instructions is so long, it looked out of whack that way:

![not-so-balanced](https://cloud.githubusercontent.com/assets/280218/12627158/eb3dc296-c544-11e5-8c69-02327344396d.png)

It is slightly more balanced this way around. 

![more-balanced](https://cloud.githubusercontent.com/assets/280218/12627162/f27db6ce-c544-11e5-8fad-949ef3fdce36.png)

Other option is to make the description of Installation instructions to fit in two lines:

![third-option](https://cloud.githubusercontent.com/assets/280218/12627168/fe4405e4-c544-11e5-89e4-e9643418e36c.png)

Which way do you think we should do it?

**Comment by pekkaklarck** [comment]
I see. I didn't notice the problem because I was viewing this on mobile where all docs were listed in one column.

Requiring explanations of each item to have a certain number of lines doesn't sound too good. Would it be possible to reserve some vertical space for each item? I don't think the layout is that bad in any of the examples, though.

A bigger problem is that if Dos and Don'ts is in the middle, referring to "above how-to" doesn't work too well. Perhaps the items could be organized so that, for example, User Guide or Public API would be alone on the bottom? Then how-to and dos/don'ts could both be on right column. Obviously should also verify that the order would be same also on mobile.

**Comment by Tattoo** [comment]
How about moving installation instructions as the lone bottom-middle one?

![screenshot](https://cloud.githubusercontent.com/assets/280218/12639377/bf2e7796-c5ac-11e5-9e8d-d3589929deef.PNG)

**Comment by pekkaklarck** [comment]
I found that one long line pretty ugly. Also, installation instructions should be first.

The doc about installation instructions could be a little shorter. Perhaps something like this:

> If you are familiar with Python and [pip](http://pip-installer.org), just run `pip install robotframework`. Notice that external libraries and tools need to be installed separately.

**Comment by Tattoo** [comment]
So like this?

![screenshot](https://cloud.githubusercontent.com/assets/280218/12640130/05dae1e4-c5b1-11e5-953f-0e932718e897.PNG)

I wouldn't move User Guide to the bottom middle as it will then be last link in mobile

**Comment by pekkaklarck** [comment]
Looks good to me. Installation doc is still a bit long but I think that's ok. Perhaps adding a forced line break after `pip install robotframework` would be a good idea, though.
