### ISSUE TITLE
Add Browser Library and Update other Libraries

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework.github.com#184]
Hi,

The new Browser library should be added to robotframework.org and there are some very old libraries that should be deleted from the page. Others like the SeleniumScreenshots should just have the correct link.

Cheers

**Comment by Tattoo** [comment]
Hi, 

Generally we do not remove libraries based on our own feelings as someone might always find them useful. For example, CNCLibrary is made by us and is still used.

I would much rather contact the given lib developers that are they maintaining it and notify if it's still used.

It would have been great if PR is for one thing only.

**Comment by Snooz82** [comment]
@Tattoo CNCLibrary is Python2 only, not maintained over the last 5 Years, has 5 Open Issues.

It will be removed.

**Comment by Snooz82** [comment]
You can update the Library and add it again.
on the last RoboCon we discussed and decided that we will remove all Py2 Only Libraries.

**Comment by Tattoo** [comment]
That seems quite a waste of everyone's resources, but have it your way. 

These things could be announced more widely than "just agreeing in Robocon". It's not like we will run out of space on the web site.

**Comment by Snooz82** [comment]
Android library - 5 Years no commit - 19 open issues
AnywhereLibrary - Py2 - 3 Years nothing
HTTP library (livetest) - Py2 - 7 Years nothing - 25 Open Issues
iOS library - Maintainer writes on GitHub that it is dead
MongoDB-Library - Py2 - 4 Years nothing - 5 Open PR - 2 trying to Add Py3
SudsLibrary - Py2 - 6 years nothing - open issues open PR
watir-robot - 9 Years nothing.

@Tattoo what are we talking about?
These Libraries are definitely dead. 
Why should we have dead garbage on our webpage?

**Comment by Tattoo** [comment]
Why do you assume some library would be "garbage" just because it hasn't been updated? It could be well-made, providing a base for someone to do a Python 3 version themselves. I can cite you examples just this year where this exact thing has happened.

In any case, I agree that some old libraries ought to be removed. However, you are going about this completely backwards. This pruning has not been communicated properly, you do it in a completely unrelated PR making history messy, and you do not contribute to a welcoming, nice community by deciding to remove things on a whim (yes, not notifying people is just that) and then ragging on people's hard work.

**Comment by Snooz82** [comment]
I think i honor peoples hard work.
And i will also add some libraries that are on github but not yet on RF.org.

RF.org is imho NOT GitHub.
It is a place where we welcome users and where we show the ecosystem of Robot Framework.

If any maintainer of these libraries would have had any interest that these libraries are still being used, (s)he should have updated to Py3 which is really not a big effort or just accept the PRs about PY3

For example the Developer of RequestsLibrary and ArchiveLibrary actively asked if we could maintain his libraries and they will be transferred to MarketSquare. These stay there.

Imho it is our (also yours) task to maintain the page. And that does also mean the content.
Feel free to contact those people and ask them to update the libraries to Py3 and we can add them back to the page.

But having the privilege to be on robotframework.org means also to give a minimum effort of maintenance.

Everyone is welcome, IF the library is working.
I consider PY2 libraries as broken. 
They stay on Pypi and Github...

**Comment by Tattoo** [comment]
I do not understand why you are being so negative and arrogant about very simple thing. I would encourage you to think your behavior, before it puts off more and more people. The way you respond in this thread is really unprofessional and definitely uncool.

**Comment by Snooz82** [comment]
Sorry for being rude!
I didn't wanted to be arrogant.

I just think that we should clean in front of our door.
And if we have not working libraries on our homepage, it is normal that people think Robotframework is old stuff. And some do!

In my opinion it is unprofessional to not maintain the page or not delete outdated information from it.
This is just maintenance. 
I don't think there is a need of pinging these developers, because non of them has done something the last years. 
RobotFramework.org has a goal to inform people about the possibilities.
Not leading into a dead end.

**Comment by Tattoo** [comment]
Yes, for example my company. As I have already stated. You literally had a response in few minutes.

I have also stated that having a library from which one can start from is not a dead end. Your actions and claims do not match here.

Finally, this is open source. We share because sharing is virtue by itself. You are here making the same kind of demands as is the classical "entitled user" archetype we have faced many times. This kind of behaviour degrades our community, especially since there would have been easy, nicer, alternative courses of actions. 

This is not about doing maintenance, of which we agree.

**Comment by IsNoGood** [comment]
Guys... I think you both have a point there. @Snooz82 idea, having only vital libraries on a fr.org would be a good idea. @Tattoo proposal, that every change should be a own PR, so it is more easier to talk case-by-case. Shall we start there?
:peace_symbol: and :heart:

**Comment by Snooz82** [comment]
Hey Tatu,

I can remove CNC-Library deletion from the PR if Eficode change it to Python 3 compatibility. 
No Problem here. I see that you started working on the issues. 👍🏼

Making every deletion in a separate PR imho makes really no sense here as it would be unnecessary effort for Sami to merge and this PR hat one goal. 
Update the Libraries list. 

As always every single line of code can be commented and changed before a complete PR is merged.

I hope this is fine.

**Comment by Tattoo** [comment]
Separate PR is literally extra minute of work for Sami. Having all deletions in a single PR where you highlight last commiter like this:

@Snooz82 - please indicate if we shouldn't list the library anymore.

would be basic courtesy and take altogether less than 10 minutes of doing.

**Comment by Snooz82** [comment]
It is not like this.
Because this PR is built to JS and ready to take live. If each Removal is a single one, sami has to build it.

In general i would say, that the foundation decides what is on the rf.org page. And we talked about the page with Pekka and some other and came to the conclusion that libraries that are not Python3 shall be removed. We officially announced on RoboCon that the next Major (4.0) of RF will deprecate Python2.

**Comment by Tattoo** [comment]
You didn't read what I wrote. 

Again, the point all along here is how you, @Snooz82 , went about doing this in a seriously uncool way. This was not the way to do it.

**Comment by Snooz82** [comment]
We can really discuss this further if you like in privat. 

But still i do not understand why removing "not working" Libraries from our page is uncool.
As you may not know, we have a lot of reappearing questions in our Community about issues with unmaintained Libraries like SudsLibrary because beginners first waste time to search the issue of a not working Library by themself.
But it wasn't their fault. The lib is py2 only. So these people waste time trying, fixing and when they are frustrated and do not know what to do, they ask and get disappointed by someone who tells them, that this library isn't maintained anymore.

It is our job to prevent this situation!

CNC-Library is back again.

**Comment by Tattoo** [comment]
Once again, I think your actions in this thread is the uncool part, not the fact that you are doing maintenance. This is now the third time I have re-iterated this.

**Comment by Snooz82** [comment]
Ok

**Comment by samipe** [comment]
Merged and panic reverted, @Snooz82 can you please resubmit PR.

The built file was not commited which broke the site. Was just about to write about this: I think for PRs a general rule would be to not include build files, only source files. Minified build files might contain malicious code as there is no way to check if it's actually the result of the build. Also if the build is done improperly, the site might break, as just happened.

**Comment by samipe** [comment]
Will update readme regarding this

**Comment by Snooz82** [comment]
@Tattoo i think i already tried to apologize for being rude.

**Comment by pekkaklarck** [comment]
Quick comments:

- This issue should have been two issues to begin with: 1) Add Browser, 2) Go through existing libs/tools and remove dead ones. FWIW, I totally agree with both.

- It's awesome someone is interested to go through the existing libs/tools.

- It would have been good to announce this more publicly to give developers time to react. It's easy to add stuff back so doing that after updates is fine as well.

- Public announcement should also mention that new libs/tools can be added there. Lot of valuable stuff is missing because nobody has asked us to add them.

- Lib/tool not being updated in several years doesn't necessarily mean its dead. It's definitely possible that it just solves a simple problem and is really that mature. Supporting only Python 2 is pretty suspicious, though.
